// Copyright (c) 2025 Tobias Bohnen
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

#pragma once

#include <tcob/app/Game.hpp>
#include <tcob/app/Platform.hpp>
#include <tcob/app/Scene.hpp>

#include <tcob/ai/Pathfinding.hpp>

#include <tcob/audio/AudioSystem.hpp>
#include <tcob/audio/Buffer.hpp>
#include <tcob/audio/Effect.hpp>
#include <tcob/audio/Music.hpp>
#include <tcob/audio/Playlist.hpp>
#include <tcob/audio/Recording.hpp>
#include <tcob/audio/Sound.hpp>
#include <tcob/audio/Source.hpp>
#include <tcob/audio/synth/SoundFont.hpp>
#include <tcob/audio/synth/SoundGenerator.hpp>
#include <tcob/audio/synth/SpeechGenerator.hpp>

#include <tcob/core/AngleUnits.hpp>
#include <tcob/core/Color.hpp>
#include <tcob/core/Common.hpp>
#include <tcob/core/Grid.hpp>
#include <tcob/core/Interfaces.hpp>
#include <tcob/core/Logger.hpp>
#include <tcob/core/Point.hpp>
#include <tcob/core/Property.hpp>
#include <tcob/core/Proxy.hpp>
#include <tcob/core/Rect.hpp>
#include <tcob/core/ServiceLocator.hpp>
#include <tcob/core/Signal.hpp>
#include <tcob/core/Size.hpp>
#include <tcob/core/Stats.hpp>
#include <tcob/core/Stopwatch.hpp>
#include <tcob/core/StringUtils.hpp>
#include <tcob/core/TaskManager.hpp>
#include <tcob/core/Timer.hpp>
#include <tcob/core/TypeFactory.hpp>
#include <tcob/core/assets/Asset.hpp>
#include <tcob/core/assets/AssetGroup.hpp>
#include <tcob/core/assets/AssetLibrary.hpp>
#include <tcob/core/assets/AssetLoader.hpp>
#include <tcob/core/assets/Assets.hpp>
#include <tcob/core/easing/Easing.hpp>
#include <tcob/core/easing/Tween.hpp>
#include <tcob/core/input/Input.hpp>
#include <tcob/core/io/FileStream.hpp>
#include <tcob/core/io/FileSystem.hpp>
#include <tcob/core/io/Filter.hpp>
#include <tcob/core/io/Magic.hpp>
#include <tcob/core/io/MemoryStream.hpp>
#include <tcob/core/io/SpanStream.hpp>
#include <tcob/core/random/Distribution.hpp>
#include <tcob/core/random/Engine.hpp>
#include <tcob/core/random/Random.hpp>

#include <tcob/data/CSV.hpp>
#include <tcob/data/Config.hpp>
#include <tcob/data/ConfigConversions.hpp>
#include <tcob/data/ConfigFile.hpp>
#include <tcob/data/ConfigSchema.hpp>
#include <tcob/data/ConfigTypes.hpp>
#include <tcob/data/Sqlite.hpp>
#include <tcob/data/SqliteColumn.hpp>
#include <tcob/data/SqliteConversions.hpp>
#include <tcob/data/SqliteDatabase.hpp>
#include <tcob/data/SqliteSavepoint.hpp>
#include <tcob/data/SqliteStatement.hpp>
#include <tcob/data/SqliteTable.hpp>

#include <tcob/gfx/Camera.hpp>
#include <tcob/gfx/Canvas.hpp>
#include <tcob/gfx/ColorGradient.hpp>
#include <tcob/gfx/Font.hpp>
#include <tcob/gfx/FontFamily.hpp>
#include <tcob/gfx/Geometry.hpp>
#include <tcob/gfx/Gfx.hpp>
#include <tcob/gfx/Image.hpp>
#include <tcob/gfx/ImageFilters.hpp>
#include <tcob/gfx/Material.hpp>
#include <tcob/gfx/Path2d.hpp>
#include <tcob/gfx/Polygon.hpp>
#include <tcob/gfx/Quadtree.hpp>
#include <tcob/gfx/Ray.hpp>
#include <tcob/gfx/RenderSystem.hpp>
#include <tcob/gfx/RenderSystemImpl.hpp>
#include <tcob/gfx/RenderTarget.hpp>
#include <tcob/gfx/RenderTexture.hpp>
#include <tcob/gfx/Renderer.hpp>
#include <tcob/gfx/ShaderProgram.hpp>
#include <tcob/gfx/TextFormatter.hpp>
#include <tcob/gfx/Texture.hpp>
#include <tcob/gfx/Transform.hpp>
#include <tcob/gfx/Transformable.hpp>
#include <tcob/gfx/UniformBuffer.hpp>
#include <tcob/gfx/VertexArray.hpp>
#include <tcob/gfx/Window.hpp>
#include <tcob/gfx/animation/Animation.hpp>
#include <tcob/gfx/animation/QuadTween.hpp>
#include <tcob/gfx/drawables/Background.hpp>
#include <tcob/gfx/drawables/Cursor.hpp>
#include <tcob/gfx/drawables/Drawable.hpp>
#include <tcob/gfx/drawables/LightingSystem.hpp>
#include <tcob/gfx/drawables/ParticleSystem.hpp>
#include <tcob/gfx/drawables/PointCloud.hpp>
#include <tcob/gfx/drawables/Shape.hpp>
#include <tcob/gfx/drawables/Text.hpp>
#include <tcob/gfx/drawables/TileMap.hpp>
#include <tcob/gfx/html/HtmlDocument.hpp>
#include <tcob/gfx/procgen/LSystem.hpp>
#include <tcob/gfx/procgen/Noise.hpp>

#include <tcob/gfx/ui/Form.hpp>
#include <tcob/gfx/ui/Layout.hpp>
#include <tcob/gfx/ui/Scrollbar.hpp>
#include <tcob/gfx/ui/Style.hpp>
#include <tcob/gfx/ui/StyleCollection.hpp>
#include <tcob/gfx/ui/Transition.hpp>
#include <tcob/gfx/ui/UI.hpp>
#include <tcob/gfx/ui/WidgetPainter.hpp>
#include <tcob/gfx/ui/WidgetTweener.hpp>
#include <tcob/gfx/ui/widgets/Accordion.hpp>
#include <tcob/gfx/ui/widgets/Button.hpp>
#include <tcob/gfx/ui/widgets/CanvasWidget.hpp>
#include <tcob/gfx/ui/widgets/Checkbox.hpp>
#include <tcob/gfx/ui/widgets/CycleButton.hpp>
#include <tcob/gfx/ui/widgets/Displays.hpp>
#include <tcob/gfx/ui/widgets/DropDownList.hpp>
#include <tcob/gfx/ui/widgets/GridView.hpp>
#include <tcob/gfx/ui/widgets/ImageBox.hpp>
#include <tcob/gfx/ui/widgets/Label.hpp>
#include <tcob/gfx/ui/widgets/ListBox.hpp>
#include <tcob/gfx/ui/widgets/Panel.hpp>
#include <tcob/gfx/ui/widgets/Progressbar.hpp>
#include <tcob/gfx/ui/widgets/Radiobutton.hpp>
#include <tcob/gfx/ui/widgets/Slider.hpp>
#include <tcob/gfx/ui/widgets/Spinner.hpp>
#include <tcob/gfx/ui/widgets/TabContainer.hpp>
#include <tcob/gfx/ui/widgets/Terminal.hpp>
#include <tcob/gfx/ui/widgets/TextBox.hpp>
#include <tcob/gfx/ui/widgets/Toggle.hpp>
#include <tcob/gfx/ui/widgets/Tooltip.hpp>
#include <tcob/gfx/ui/widgets/Widget.hpp>
#include <tcob/gfx/ui/widgets/WidgetContainer.hpp>

#include <tcob/physics/Body.hpp>
#include <tcob/physics/DebugDraw.hpp>
#include <tcob/physics/Joint.hpp>
#include <tcob/physics/Shape.hpp>
#include <tcob/physics/World.hpp>

#include <tcob/scripting/Script.hpp>
#include <tcob/scripting/Scripting.hpp>
#include <tcob/scripting/Wrapper.hpp>
#include <tcob/scripting/lua/Lua.hpp>
#include <tcob/scripting/lua/LuaClosure.hpp>
#include <tcob/scripting/lua/LuaConversions.hpp>
#include <tcob/scripting/lua/LuaScript.hpp>
#include <tcob/scripting/lua/LuaTypes.hpp>
#include <tcob/scripting/lua/LuaWrapper.hpp>
#include <tcob/scripting/squirrel/Squirrel.hpp>
#include <tcob/scripting/squirrel/SquirrelClosure.hpp>
#include <tcob/scripting/squirrel/SquirrelConversions.hpp>
#include <tcob/scripting/squirrel/SquirrelScript.hpp>
#include <tcob/scripting/squirrel/SquirrelTypes.hpp>
