name: Asan

on:
  workflow_dispatch 

jobs:
  build:
    runs-on: ubuntu-24.04
    name:    ${{matrix.build_type}}
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Debug']
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - name:  Install compiler and deps
      run:   wget https://apt.llvm.org/llvm.sh; chmod +x llvm.sh; sudo ./llvm.sh 21; sudo apt-get install -y libc++-21-dev libc++abi-21-dev libsdl2-dev
      shell: bash
       
    - name:  Configure CMake
      run:   cmake -B ./build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DTCOB_IS_CI=ON -DTCOB_ASAN=ON -DTCOB_BUILD_EXAMPLES=OFF -DTCOB_BUILD_GAMES=OFF -DTCOB_BUILD_TOOLS=OFF
      shell: bash
      env:
         CC:       clang-21
         CXX:      clang++-21
         CXXFLAGS: -stdlib=libc++ -fexperimental-library

    - name:  Build
      run:   cmake --build ./build --config ${{matrix.build_type}} -j 8
      shell: bash
      env:
         CC:       clang-21
         CXX:      clang++-21
         CXXFLAGS: -stdlib=libc++ -fexperimental-library
         
    - name: Test
      run:  ctest -C ${{matrix.build_type}} -j 8
      working-directory: ./build
      env:
         CTEST_OUTPUT_ON_FAILURE: 1
